"""
Simulator models
================
Stores simulation runs so users can share or revisit them.
The core logic lives in services.py.
"""

from django.db import models
from apps.tipping_points.models import TippingPoint


class SimulationScenario(models.Model):
    """
    A named preset scenario for the simulator (e.g., 'High emissions, low action').
    Pre-loads the sliders with meaningful values so newcomers can explore quickly.
    """
    name        = models.CharField(max_length=150, unique=True)
    slug        = models.SlugField(unique=True)
    description = models.TextField()
    is_featured = models.BooleanField(default=False)

    # Slider defaults for this scenario (0–100 scale)
    default_misinformation    = models.IntegerField(default=50)
    default_media_literacy    = models.IntegerField(default=50)
    default_public_trust      = models.IntegerField(default=50)
    default_policy_speed      = models.IntegerField(default=50)
    default_emissions         = models.IntegerField(default=50)
    default_resilience        = models.IntegerField(default=50)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-is_featured', 'name']

    def __str__(self):
        return self.name


class SimulationRun(models.Model):
    """
    Records one execution of the domino simulator.
    Anonymous runs are fine; session_key links to a Django session if needed.
    """
    session_key = models.CharField(max_length=40, blank=True)
    scenario    = models.ForeignKey(
        SimulationScenario,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name='runs',
    )

    # inputs (0–100 integer sliders) 
    misinformation  = models.IntegerField()
    media_literacy  = models.IntegerField()
    public_trust    = models.IntegerField()
    policy_speed    = models.IntegerField()
    emissions       = models.IntegerField()
    resilience      = models.IntegerField()

    # computed outputs 
    trust_score     = models.FloatField()
    delay_risk      = models.FloatField()
    climate_pressure= models.FloatField()

    # plain-text summary generated by the service
    narrative       = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'Run {self.pk} – pressure {self.climate_pressure:.1f}'


class ActivatedNode(models.Model):
    """
    Which tipping points were activated in a given simulation run.
    """
    run          = models.ForeignKey(SimulationRun, related_name='activated_nodes', on_delete=models.CASCADE)
    tipping_point = models.ForeignKey(TippingPoint, on_delete=models.CASCADE)
    activation_score = models.FloatField(
        help_text='0–1 probability/activation level assigned by the simulation logic.'
    )
    triggered_by = models.CharField(
        max_length=200, blank=True,
        help_text='Comma-separated slugs of nodes that triggered this activation.',
    )

    class Meta:
        ordering = ['-activation_score']

    def __str__(self):
        return f'{self.tipping_point.slug} ({self.activation_score:.2f})'
